### ISSUE TITLE
the block write method

### ISSUE THREAD

**Issue by oranger34** [ClydeProjects/EagleTree#8]
Hi
I am reading the code of this project.

I do not quite understand this line in block.cpp:

enum status Block::write(Event &event)
{
	if (event.get_address().page > 0 && data[event.get_address().page - 1].get_state() == EMPTY) {
		printf("\n");
		event.print();
		assert(data[event.get_address().page - 1].get_state() **!= EMPTY**);
	}
	enum status ret = data[event.get_address().page]._write(event);
	pages_valid++;
	return ret;
}

Why the assertion is "the state is not EMPTY"?

I think it should be EMPTY.

I am very confused.

**Comment by nivdayan** [comment]
Hello,

The point of this is check is to ensure that we are not writing page X in a
block if page X-1 on the same block has still not been written. This is to
ensure that writes are sequential within a block. The assertion just makes
the program fail if this is violated.

Best,
Niv
